// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txaufrrjucwfsfreskcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4YXVmcnJqdWN3ZnNmcmVza2NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDI5NTksImV4cCI6MjA2NDUxODk1OX0.FJUs471jzAWbjf10ghnVDGWLpKoMQX-stL2WnKKbzIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);